### ISSUE TITLE
About the maximum word length set to 20

### ISSUE THREAD

**Issue by toruurakawa** [malllabiisc/DiPS#11]
In the paper and the implementation, the maximum token (=word) length of the dataset is truncated up to 20 tokens, but I'm not sure the reason why you set such a condition.

Would you tell me more about this setting, like why you set this limitation and whether you have a paper that you referenced for it or empirical findings about that ?

Thanks.

**Comment by ashutoshml** [comment]
While the model is capable of working without setting a max length, we performed a truncation in order to reduce the training complexity of the model. This is in line with (https://www.aclweb.org/anthology/C16-1275.pdf) [See data selection, section 4.1], and (https://arxiv.org/pdf/1709.05074.pdf) [See datasets subsection in experiments]. 
While our model is capable of handling longer sequences, the "non-attention-model" based baseline scores take a big hit and it becomes a slightly unfair comparison. This is because it is difficult to cram the meaning of the sentence in a single vector (see https://machinethoughts.wordpress.com/2017/09/01/deep-meaning-beyond-thought-vectors/)

If I am not mistaken, some preliminary statistical analyses indicated that most of the sentences have token length <=20. 

You may remove that condition and the model should ideally work fine.

**Comment by toruurakawa** [comment]
Thank you for your quick and detailed answer, I understand the reason for the configuration and that the DiPS model can work without it.

> If I am not mistaken, some preliminary statistical analyses indicated that most of the sentences have token length <=20.

Yes. In the calculation at hand, min / max token length is 4 / 36 and the mean is 11, 4.8% have token length over 20 (for the test data).
