### ISSUE TITLE
What is the maximum number of paraphrases can be generated for single input sentence?

### ISSUE THREAD

**Issue by aijiewil** [malllabiisc/DiPS#12]
Hi.
I'm trying to generate 500 paraphrases for each input sentence. But I got "Error in Submod: attempt to get argmax of an empty sequence". And I found that there are only 50 paraphrases generated for each sentence in the output file. I'm wondering if you can tell me the maximum number of paraphrases can be generated for single input sentence, or how can I get more paraphrases using DiPS.
Thanks.
Merry Christmas and Happy New Year!

**Comment by ashutoshml** [comment]
Hi @aijiewil 

Although not advisable, you can ideally generate as many paraphrases as you want by setting `outer_width` and `inner_width` accordingly [here](https://github.com/malllabiisc/DiPS/blob/8ea9747b1c104b6490000cdff15a522e9b860c05/src/model.py#L278). Set it to >1000 and 20/30, respectively. (and the beam_width args to 500)

The problem with generating such high number of paraphrases are two folds:

1. It is _almost_ impossible for one sentence to have such a high number of lexically diverse paraphrases.
2. Our system will possibly generate a lot of non-paraphrastic sentences when the width is this huge since it relies on beam search and the trained seq2seq model, which might not be the perfect system. 
3. Setting high beam_width is computationally expensive and hence not advisable.

Happy New Year!

Thanks for writing in.
